-- Governance: three least-privilege roles, PII masking, append-only decisions,
-- and ground truth hidden from everyone who works alerts. Run after every other script
-- (02_canonical recreates tables, which drops their grants).
--
-- Note: users default to DEFAULT_SECONDARY_ROLES = ('ALL'), so a session "as AUDITOR" still
-- carries the user's other roles' privileges. Masking therefore checks CURRENT_ROLE() (the
-- primary role), and scripts/check_governance.py runs USE SECONDARY ROLES NONE before testing.

CREATE ROLE IF NOT EXISTS AML_ANALYST        COMMENT = 'Works alerts: investigates, decides, drafts SARs';
CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER COMMENT = 'Approves and files SARs; everything an analyst can do';
CREATE ROLE IF NOT EXISTS AUDITOR            COMMENT = 'Read-only; customer PII masked';
GRANT ROLE AML_ANALYST TO ROLE COMPLIANCE_OFFICER;
GRANT ROLE COMPLIANCE_OFFICER TO ROLE SYSADMIN;
GRANT ROLE AUDITOR TO ROLE SYSADMIN;

-- Read access for all three.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AML_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AUDITOR;
GRANT USAGE ON DATABASE RISK_COPILOT TO ROLE AML_ANALYST;
GRANT USAGE ON DATABASE RISK_COPILOT TO ROLE AUDITOR;
GRANT USAGE ON SCHEMA RISK_COPILOT.AML TO ROLE AML_ANALYST;
GRANT USAGE ON SCHEMA RISK_COPILOT.AML TO ROLE AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA RISK_COPILOT.AML TO ROLE AML_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA RISK_COPILOT.AML TO ROLE AML_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RISK_COPILOT.AML TO ROLE AUDITOR;
GRANT SELECT ON ALL VIEWS  IN SCHEMA RISK_COPILOT.AML TO ROLE AUDITOR;

-- Ground truth is for evaluation only: nobody who works alerts may see it.
-- (RULE_METRICS still works for them: a view runs with its owner's rights.)
REVOKE SELECT ON TABLE RISK_COPILOT.AML.TXN_LABELS FROM ROLE AML_ANALYST;
REVOKE SELECT ON TABLE RISK_COPILOT.AML.RAW_LABELS FROM ROLE AML_ANALYST;
REVOKE SELECT ON TABLE RISK_COPILOT.AML.TXN_LABELS FROM ROLE AUDITOR;
REVOKE SELECT ON TABLE RISK_COPILOT.AML.RAW_LABELS FROM ROLE AUDITOR;

-- AI layer.
GRANT SELECT ON SEMANTIC VIEW RISK_COPILOT.AML.AML_SEMANTIC_VIEW TO ROLE AML_ANALYST;
GRANT SELECT ON SEMANTIC VIEW RISK_COPILOT.AML.AML_SEMANTIC_VIEW TO ROLE AUDITOR;
GRANT USAGE ON CORTEX SEARCH SERVICE RISK_COPILOT.AML.AML_POLICY_SEARCH TO ROLE AML_ANALYST;
GRANT USAGE ON CORTEX SEARCH SERVICE RISK_COPILOT.AML.AML_POLICY_SEARCH TO ROLE AUDITOR;
GRANT USAGE ON AGENT RISK_COPILOT.AML.AML_COPILOT TO ROLE AML_ANALYST;
GRANT USAGE ON AGENT RISK_COPILOT.AML.AML_COPILOT TO ROLE AUDITOR;

-- Writes. Analysts record decisions and drafts but can never edit or delete one:
-- INSERT only on FINDINGS and SAR_REPORTS, no UPDATE / DELETE. That is what makes the
-- decision log append-only for the people who write it.
GRANT INSERT ON TABLE RISK_COPILOT.AML.FINDINGS    TO ROLE AML_ANALYST;
GRANT INSERT ON TABLE RISK_COPILOT.AML.SAR_REPORTS TO ROLE AML_ANALYST;
GRANT UPDATE ON TABLE RISK_COPILOT.AML.ALERTS      TO ROLE AML_ANALYST;   -- alert STATUS
-- Only a compliance officer moves a SAR from DRAFT to APPROVED / FILED.
GRANT UPDATE ON TABLE RISK_COPILOT.AML.SAR_REPORTS TO ROLE COMPLIANCE_OFFICER;

-- PII masking. Masking policies need Enterprise edition; this trial is Standard
-- ("Unsupported feature 'MASKING POLICY'"), so masking lives in secure views instead, and the
-- auditor loses direct access to every table that holds a name. On Enterprise, swap these for
-- a PII tag with a tag-based masking policy on CUSTOMERS.NAME.
-- The secure views themselves are created in 60_semantic_view.sql (the semantic view uses them).
REVOKE SELECT ON TABLE RISK_COPILOT.AML.CUSTOMERS     FROM ROLE AUDITOR;
REVOKE SELECT ON TABLE RISK_COPILOT.AML.RAW_CUSTOMERS FROM ROLE AUDITOR;
REVOKE SELECT ON TABLE RISK_COPILOT.AML.SAR_REPORTS   FROM ROLE AUDITOR;
GRANT SELECT ON VIEW RISK_COPILOT.AML.CUSTOMER_PROFILE TO ROLE AUDITOR;
GRANT SELECT ON VIEW RISK_COPILOT.AML.SAR_REVIEW       TO ROLE AUDITOR;
GRANT SELECT ON VIEW RISK_COPILOT.AML.CUSTOMER_PROFILE TO ROLE AML_ANALYST;
GRANT SELECT ON VIEW RISK_COPILOT.AML.SAR_REVIEW       TO ROLE AML_ANALYST;
