-- The command centre, deployed twice. A Streamlit app runs with its owner's role, so ownership
-- is the access control: the officer copy can decide and approve; the auditor copy is
-- read-only with PII masked, enforced by Snowflake rather than by the app.
-- Ownership of a Streamlit can't be transferred, so each copy is created by its owning role;
-- CREATE STREAMLIT is granted only for the duration of this script.
-- Upload first (deploy.py does this): PUT streamlit/* @APP_STAGE

CREATE STAGE IF NOT EXISTS APP_STAGE;
GRANT READ ON STAGE APP_STAGE TO ROLE COMPLIANCE_OFFICER;
GRANT READ ON STAGE APP_STAGE TO ROLE AUDITOR;
GRANT CREATE STREAMLIT ON SCHEMA RISK_COPILOT.AML TO ROLE COMPLIANCE_OFFICER;
GRANT CREATE STREAMLIT ON SCHEMA RISK_COPILOT.AML TO ROLE AUDITOR;
-- dropped as admin first: a copy owned by any other role can't be replaced by the new owner
DROP STREAMLIT IF EXISTS RISK_COPILOT.AML.AML_COMMAND_CENTRE;
DROP STREAMLIT IF EXISTS RISK_COPILOT.AML.AML_AUDIT_VIEW;
USE SECONDARY ROLES NONE;

USE ROLE COMPLIANCE_OFFICER;
CREATE OR REPLACE STREAMLIT RISK_COPILOT.AML.AML_COMMAND_CENTRE
    FROM @RISK_COPILOT.AML.APP_STAGE
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = COMPUTE_WH
    RUNTIME_NAME = 'SYSTEM$WAREHOUSE_RUNTIME'   -- reads environment.yml; the default is now the
    TITLE = 'AML Risk Copilot';                  -- container runtime, which wants pyproject.toml
ALTER STREAMLIT RISK_COPILOT.AML.AML_COMMAND_CENTRE ADD LIVE VERSION FROM LAST;

USE ROLE AUDITOR;
CREATE OR REPLACE STREAMLIT RISK_COPILOT.AML.AML_AUDIT_VIEW
    FROM @RISK_COPILOT.AML.APP_STAGE
    MAIN_FILE = 'streamlit_app.py'
    QUERY_WAREHOUSE = COMPUTE_WH
    RUNTIME_NAME = 'SYSTEM$WAREHOUSE_RUNTIME'
    TITLE = 'AML Risk Copilot (Auditor)';
ALTER STREAMLIT RISK_COPILOT.AML.AML_AUDIT_VIEW ADD LIVE VERSION FROM LAST;

USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES ALL;
REVOKE CREATE STREAMLIT ON SCHEMA RISK_COPILOT.AML FROM ROLE COMPLIANCE_OFFICER;
REVOKE CREATE STREAMLIT ON SCHEMA RISK_COPILOT.AML FROM ROLE AUDITOR;

SHOW STREAMLITS IN SCHEMA RISK_COPILOT.AML;
